### PR TITLE
Add option to output read probabilities.

### PR DESCRIPTION
**Pull request by zertan**
Added option "--phi" to output read probabilities to each (mapped) transcript. The output variable was the "SimpleSparse" phi in VariationalBayes.cpp.

### CODE REVIEW

**Comment by ahonkela** [comment]
Thanks, this looks great!

I am wondering if the output should contain the read names like .prob files do. That might be a useful extra layer of security to help avoid mistakes in the followup analysis.

How does this work for your analysis - do you use the read names? If you are getting them anyway it might be cleaner to do the right thing right away.

Antti

**Comment by zertan** [comment]
Yes that is better! Added read names to the output by reopening the .prob file.

**Review by ahonkela — COMMENTED** [review]
Thanks again, this looks great!
I have only one minor comment about the option name - if you can fix that easily that may be easiest, otherwise I can probably merge as is and fix it afterwards.

Antti

**Comment by zertan** [comment]
Yes that is better. //Daniel

**Comment by ahonkela** [comment]
Thanks a lot for your quick response! I am very sorry for the long delay in my response - I have been too busy with other things lately.

I tested the code and it seems to work great!

I have just one final request: can you write somewhere (perhaps just replying to this message) that you agree to release your changes under the Artistic 2.0 license used in the BitSeq code.

Thanks again for you contribution!

Antti

**Comment by zertan** [comment]
Yep I agree to release the changes under the Artistic 2.0 license in the BitSeq code. Thank you! //Daniel

**Comment by ahonkela** [comment]
Thanks!

Antti

**Pull request merged**
